# Generated by Django 5.2.6 on 2025-09-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
